### ISSUE TITLE
Bastion URLS not working in us-east-1

### ISSUE THREAD

**Issue by techcto** [aws-quickstart/quickstart-amazon-eks#133]
This commit: 6b2294a4e0f2d2e03013a43d856e96c6e8085afd

Is causing errors on self hosted scripts.

2020-04-23 21:45:59,772 P8603 [INFO]    setup_os Ended
2020-04-23 21:45:59,772 P8603 [INFO]    setup_logs Started
2020-04-23 21:45:59,772 P8603 [INFO]      % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
2020-04-23 21:45:59,772 P8603 [INFO]                                     Dload  Upload   Total   Spent    Left  Speed
2020-04-23 21:45:59,772 P8603 [INFO]
2020-04-23 21:45:59,772 P8603 [INFO]      0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (6) Could not resolve host: amazoncloudwatch-agent-us-east-1.s3.us-east-1
2020-04-23 21:45:59,772 P8603 [INFO] ------------------------------------------------------------
2020-04-23 21:45:59,772 P8603 [ERROR] Exited with error code 6

**Comment by techcto** [comment]
If you revert this code back,

`    if [[ "${release}" == "SLES" ]]; then
        curl 'https://amazoncloudwatch-agent.s3.amazonaws.com/suse/amd64/latest/amazon-cloudwatch-agent.rpm' -O
        zypper install --allow-unsigned-rpm -y ./amazon-cloudwatch-agent.rpm
        rm ./amazon-cloudwatch-agent.rpm
    elif [[ "${release}" == "CentOS" ]]; then
        curl 'https://amazoncloudwatch-agent.s3.amazonaws.com/centos/amd64/latest/amazon-cloudwatch-agent.rpm' -O
        rpm -U ./amazon-cloudwatch-agent.rpm
        rm ./amazon-cloudwatch-agent.rpm
    elif [[ "${release}" == "Ubuntu" ]]; then
        curl 'https://amazoncloudwatch-agent.s3.amazonaws.com/ubuntu/amd64/latest/amazon-cloudwatch-agent.deb' -O
        dpkg -i -E ./amazon-cloudwatch-agent.deb
        rm ./amazon-cloudwatch-agent.deb
    elif [[ "${release}" == "AMZN" ]]; then
        curl 'https://amazoncloudwatch-agent.s3.amazonaws.com/amazon_linux/amd64/latest/amazon-cloudwatch-agent.rpm' -O
        rpm -U ./amazon-cloudwatch-agent.rpm
        rm ./amazon-cloudwatch-agent.rpm
    fi`

It works with self-hosted.  Not sure if this is a region thing.

**Comment by jaymccon** [comment]
can you provide any errors from `/var/log/cfn-init*.log` on the bastion? I'm unable to replicate this when I self host.

**Comment by techcto** [comment]
I should have provided more info, I was missing these vars.  ${REGION}.s3.${REGION}.${URL_SUFFIX}.  I will pull the latest commits and test again.

**Comment by techcto** [comment]
Just tried again with no luck.  Got this. 

verify_dependencies Ended
Setting up bastion session log in /var/log/bastion/bastion.log
BANNER_PATH = s3://***-quickstarts/***/scripts/bastion_banner_message.txt
Creating Banner in /etc/ssh_banner
usage: aws [options] <command> <subcommand> [<subcommand> ...] [parameters]
To see help text, you can run:

  aws help
  aws <command> help
  aws <command> <subcommand> help
aws: error: argument --region: expected one argument

2020-05-12 12:07:36,294 [ERROR] Error encountered during build of config: Command b-bootstrap failed
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/cfnbootstrap/construction.py", line 542, in run_config
    CloudFormationCarpenter(config, self._auth_config).build(worklog)
  File "/usr/lib/python2.7/dist-packages/cfnbootstrap/construction.py", line 260, in build
    changes['commands'] = CommandTool().apply(self._config.commands)
  File "/usr/lib/python2.7/dist-packages/cfnbootstrap/command_tool.py", line 117, in apply
    raise ToolError(u"Command %s failed" % name)
ToolError: Command b-bootstrap failed
2020-05-12 12:07:36,296 [ERROR] -----------------------BUILD FAILED!------------------------
2020-05-12 12:07:36,299 [ERROR] Unhandled exception during build: Command b-bootstrap failed
Traceback (most recent call last):
  File "/usr/bin/cfn-init", line 171, in <module>
    worklog.build(metadata, configSets)
  File "/usr/lib/python2.7/dist-packages/cfnbootstrap/construction.py", line 129, in build
    Contractor(metadata).build(configSets, self)
  File "/usr/lib/python2.7/dist-packages/cfnbootstrap/construction.py", line 530, in build
    self.run_config(config, worklog)
  File "/usr/lib/python2.7/dist-packages/cfnbootstrap/construction.py", line 542, in run_config
    CloudFormationCarpenter(config, self._auth_config).build(worklog)
  File "/usr/lib/python2.7/dist-packages/cfnbootstrap/construction.py", line 260, in build
    changes['commands'] = CommandTool().apply(self._config.commands)
  File "/usr/lib/python2.7/dist-packages/cfnbootstrap/command_tool.py", line 117, in apply
    raise ToolError(u"Command %s failed" % name)
ToolError: Command b-bootstrap failed
****
