### ISSUE TITLE
eiifccuhentrnvlkbjhfjudnkufkfertrkdujekeffhg

### ISSUE THREAD

**Issue by nilada** [aws-quickstart/quickstart-amazon-eks#399]
eks-quickstart-RegionalSharedResources" is failing with error - "CloudFormation did not receive a response from your Custom Resource. Please check your logs for requestId [23fcde0d-474a-4792-85c0-6463ad09e284]. If you are using the Python cfn-response module, you may need to update your Lambda function code so that CloudFormation can attach the updated version."

**Comment by gkudikala** [comment]
Any update on this Issue? CFT is failing at preReq

**Comment by jebinjeb** [comment]
+1

**Comment by awsari** [comment]
I found the root cause of this and there must have been a change which I have not researched.
**Environment:**

1. Syncing the public aws-quickstart bucket to a local directory
2. Syncing from the local directory to an s3 account bucket

an account s3 bucket

Old Version in registerType and registerCustomResource lambdas:

```
from .base import compare, match, validate, SimpleSpec, NpmSpec, Spec, SpecItem, Version


__author__ = "Raphaël Barrois <raphael.barrois+semver@polytechnique.org>"
__version__ = '2.8.5'
```

The new version for the lambdas is: 

```
from .base import compare, match, validate, SimpleSpec, NpmSpec, Spec, SpecItem, Version


__author__ = "Raphaël Barrois <raphael.barrois+semver@polytechnique.org>"
try:
    # Python 3.8+
    from importlib.metadata import version

    __version__ = version("semantic_version")
except ImportError:
    import pkg_resources

    __version__ = pkg_resources.get_distribution("semantic_version").version
```
**Error in log**
```
DistributionNotFound: The 'semantic_version' distribution was not found and is required by the application Traceback (most recent call last):   File "/var/lang/lib/python3.8/imp.py", line 234, in load_module     return load_source(name, filename, file)   File "/var/lang/lib/python3.8/imp.py", line 171, in load_source     module = _load(spec)   File "<frozen importlib._bootstrap>", line 702, in _load   File "<
```

**Theory**
It seems to need the semantic_version defined and it isn't or something related to the version function dep.
